spring.application.name=demo

spring.datasource.url=jdbc:postgresql://diknivqnzpmmmzssojjg.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

server.port=8081
springdoc.swagger-ui.path=/swagger-ui/index.html

supabase.url=https://diknivqnzpmmmzssojjg.supabase.co
supabase.anon-key=
supabase.service-key=


